### ISSUE TITLE
alternate <esc> mappings don't work

### ISSUE THREAD

**Issue by ParkerHGordon** [personalizedrefrigerator/joplin-plugin-codemirror-vimrc#1]
Hi, thanks for you work on this! I've gotten used to using "jk" and "kj" as my go to way of exiting insert and visual modes, so I normally have mappings such as this in my .vimrc. Below is the full text I put into the joplin vimrc file. I'm on Mac.

```
" A .vimrc-like file. At present, very little is supported.
" You can use the commands:
"   inoremap
"   vnoremap
"   nnoremap
"   imap
"   nmap
"   vmap
"   unmap
" Because commands are passed directly to CodeMirror's ViM API,
" insert-mode mappings seem to be unable to insert text.

inoremap jk <esc>
inoremap kj <esc>
vnoremap jk <esc>
vnoremap kj <esc>

" press F5 to unhighlight search results (this also doesn't seem to work)
nnoremap <F5> :noh<CR>
```
When I put this in the vimrc-like file your plugin provides and I hit "ok", "kj" and "jk" don't seem to do anything special (they just type as normal). If I use imap instead of inoremap, they won't type at least (so it seems like the mapping may have worked) but they still don't exit from insert mode the way you'd expect <esc> to. 
Thanks again for the plugin!

**Comment by personalizedrefrigerator** [comment]
These modifications of the above commands seem to work:
- `imap jk <Esc>` (with a capital `E`)
- `nmap <F5> :noh<CR>`


Note that this plugin does little more than call CodeMirror's built-in `map`/`unmap`/`noremap` functions:
https://github.com/personalizedrefrigerator/joplin-plugin-codemirror-vimrc/blob/51f598f333a3b94d938fe9cb1ab5be3aba4d002f/src/contentScripts/codeMirrorPlugin.ts#L77-L78


`nnoremap [ j` does seem to work, I suspect that the CodeMirror `noremap` function doesn't support mapping to escape/enter.

It might make sense for examples of what does/doesn't work to be added to the default `.vimrc`-like file.

Thank you for reporting this!

**Comment by personalizedrefrigerator** [comment]
I've added examples to the default configuration file and published a new release! It should be available within a few days.

**Comment by ParkerHGordon** [comment]
Oh sweet! Thanks for looking into this, works for me now!
