### ISSUE TITLE
Setting button to delete broken vimrc

### ISSUE THREAD

**Issue by shinglyu** [personalizedrefrigerator/joplin-plugin-codemirror-vimrc#2]
Thank you for the great plugin!

I made some typo in the vimrc and the file is corrupted. When I type `:vimrc` it doesn't open the vimrc editor popup anymore. 

I had to manually go into `~/.config/joplin-desktop/plugin-data/io.github.personalizedrefrigerator.joplin-vimrc/.vimrc` to fix it. 

It would be great to have a plugin setting page with a button to reset the vimrc to empty.

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

I can reproduce this (but only with the non-beta CodeMirror 5 editor).

**Comment by personalizedrefrigerator** [comment]
Here's what seems to be happening:
1. The plugin shows an alert dialog reporting an error in the `.vimrc`
2. The user clicks "OK"
3. The plugin shows **another** error dialog in the background (it seems that the plugin is reloaded several times in a row?). At least one of the error dialogs is shown behind the Joplin window.
4. This dialog is an `alert` dialog, so the plugin pauses until it is dismissed.
